/**
 * Fails if any source file is invisible to git.
 *
 * The Logs screen 404'd on a fresh checkout for hours while working perfectly
 * here. The parent repository's .gitignore contains "logs" — the ordinary Node
 * rule for log files — and that pattern matches ANY directory of that name,
 * so app/logs/page.tsx was never committed. Nothing local catches this: the
 * file exists, it compiles, it type-checks, it renders. It simply isn't in the
 * repository, and only someone else's checkout ever finds out.
 *
 * So: ask git, for every source file, whether it can actually see it.
 *
 * Run: pnpm check:tracked (part of pnpm verify)
 */
import { readdirSync, statSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_DIRS = ["app", "convex", "packages", "scripts", "worker", "config", "templates"];
const SKIP = new Set(["node_modules", ".next", "out", "_generated"]);
// Genuinely generated, genuinely ignored, and regenerated by pnpm prompts:build.
const EXPECTED_IGNORED = [/prompts\.generated\.ts$/, /\.tsbuildinfo$/];

function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (SKIP.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (/\.(tsx?|mjs|js|md|ya?ml|css|json)$/.test(entry)) out.push(full);
  }
  return out;
}

const files = SOURCE_DIRS.flatMap((d) => walk(join(root, d)));
const relatives = files.map((f) => relative(root, f).replace(/\\/g, "/"));

// One call, not one per file.
const result = spawnSync("git", ["check-ignore", "--stdin"], {
  cwd: root,
  input: relatives.join("\n"),
  encoding: "utf8",
});

const ignored = (result.stdout ?? "")
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean)
  .filter((f) => !EXPECTED_IGNORED.some((re) => re.test(f)));

if (ignored.length > 0) {
  console.error(
    `\n${ignored.length} source file(s) are ignored by git and would be missing from a fresh checkout:\n`,
  );
  for (const f of ignored) {
    const why = spawnSync("git", ["check-ignore", "-v", f], { cwd: root, encoding: "utf8" });
    console.error(`  ${f}\n      ignored by: ${(why.stdout ?? "").trim().split("\t")[0]}`);
  }
  console.error(
    "\nAdd a negation to office/.gitignore. Git will not descend into an excluded\n" +
      "directory, so un-exclude the directory before its contents:\n" +
      "  !/app/thing/\n  !/app/thing/**\n",
  );
  process.exit(1);
}

console.log(`Tracked OK — all ${relatives.length} source files are visible to git.`);
